# Generated by Django 3.2.10 on 2022-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='goal',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='prog',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
